import io
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN

# --- Color Constants ---
COLORS = {
    "primary": RGBColor(15, 23, 42),       # Dark Navy Slate (#0F172A)
    "accent_blue": RGBColor(96, 165, 250), # Light Blue (#60A5FA)
    "white": RGBColor(255, 255, 255),
    "subtitle_blue": RGBColor(219, 234, 254), # Soft Blue (#DBEAFE)
    "text_dark": RGBColor(51, 65, 85),     # Slate 700
    "heading_blue": RGBColor(37, 99, 235),  # Accent Blue (#2563EB)
    "muted_gray": RGBColor(148, 163, 184)  # Muted Gray
}

def add_cover(prs: Presentation, data: dict):
    """
    Creates the styled cover slide matching your pptxgenjs layout.
    """
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)

    # 1. Dark Background Fill
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = COLORS["primary"]

    # 2. Top Decorative Accent Rectangle Bar (x:0, y:0, w:13.33, h:0.18)
    shape = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        Inches(0), Inches(0), Inches(13.333), Inches(0.18)
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = COLORS["accent_blue"]
    shape.line.color.rgb = COLORS["accent_blue"]

    # 3. Main Title Text Box
    tx_box = slide.shapes.add_textbox(Inches(0.7), Inches(1.7), Inches(12), Inches(1.2))
    tf = tx_box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = data.get("title", "Untitled Presentation")
    p.font.size = Pt(28)
    p.font.bold = True
    p.font.name = "Aptos"
    p.font.color.rgb = COLORS["white"]
    p.alignment = PP_ALIGN.CENTER

    # 4. Subtitle Text Box
    if data.get("subtitle"):
        sub_box = slide.shapes.add_textbox(Inches(1.0), Inches(2.8), Inches(11.33), Inches(0.8))
        stf = sub_box.text_frame
        stf.word_wrap = True
        sp = stf.paragraphs[0]
        sp.text = data.get("subtitle")
        sp.font.size = Pt(15)
        sp.font.name = "Aptos"
        sp.font.color.rgb = COLORS["subtitle_blue"]
        sp.alignment = PP_ALIGN.CENTER


def add_content_slide(prs: Presentation, title: str, points: list, current_index: int, total_slides: int):
    """
    Creates a clean content slide with title, bullet points, and slide counter footer.
    """
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)

    # 1. Top Decorative Accent Line
    shape = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE,
        Inches(0), Inches(0), Inches(13.333), Inches(0.1)
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = COLORS["heading_blue"]
    shape.line.fill.background()

    # 2. Slide Title
    t_box = slide.shapes.add_textbox(Inches(0.8), Inches(0.6), Inches(11.7), Inches(1.0))
    tf = t_box.text_frame
    tf.word_wrap = True
    tp = tf.paragraphs[0]
    tp.text = title
    tp.font.size = Pt(24)
    tp.font.bold = True
    tp.font.name = "Aptos"
    tp.font.color.rgb = COLORS["heading_blue"]

    # 3. Bullet Points Container
    c_box = slide.shapes.add_textbox(Inches(0.8), Inches(1.8), Inches(11.7), Inches(4.8))
    cf = c_box.text_frame
    cf.word_wrap = True

    for idx, point in enumerate(points):
        p = cf.paragraphs[0] if idx == 0 else cf.add_paragraph()
        p.text = f"•  {point}"
        p.font.size = Pt(15)
        p.font.name = "Aptos"
        p.font.color.rgb = COLORS["text_dark"]
        p.space_after = Pt(12)

    # 4. Footer Slide Counter (e.g. "Slide 1 of 6")
    f_box = slide.shapes.add_textbox(Inches(10.5), Inches(6.8), Inches(2.0), Inches(0.4))
    ff = f_box.text_frame
    fp = ff.paragraphs[0]
    fp.text = f"Slide {current_index} of {total_slides}"
    fp.font.size = Pt(10)
    fp.font.name = "Aptos"
    fp.font.color.rgb = COLORS["muted_gray"]
    fp.alignment = PP_ALIGN.RIGHT


def add_thank_you(prs: Presentation):
    """
    Creates a styled closing slide matching the cover theme.
    """
    blank_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(blank_layout)

    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = COLORS["primary"]

    tx_box = slide.shapes.add_textbox(Inches(1.0), Inches(3.0), Inches(11.33), Inches(1.5))
    tf = tx_box.text_frame
    p = tf.paragraphs[0]
    p.text = "Thank You!"
    p.font.size = Pt(36)
    p.font.bold = True
    p.font.name = "Aptos"
    p.font.color.rgb = COLORS["white"]
    p.alignment = PP_ALIGN.CENTER

    sp = tf.add_paragraph()
    sp.text = "Generated by CortexAI"
    sp.font.size = Pt(14)
    sp.font.name = "Aptos"
    sp.font.color.rgb = COLORS["subtitle_blue"]
    sp.alignment = PP_ALIGN.CENTER
    sp.space_before = Pt(10)


def generate_ppt(data: dict) -> bytes:
    """
    Main orchestration function matching your pptxgenjs logic:
    1. Initialize Presentation with 16:9 widescreen layout
    2. Add Cover
    3. Loop through slides
    4. Add Thank You slide
    """
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Add Cover Slide
    add_cover(prs, data)

    # Add Content Slides
    slides = data.get("slides", [])
    total_slides = len(slides)

    for i, s in enumerate(slides):
        title = s.get("title", f"Slide {i + 1}")
        points = s.get("points", [])
        add_content_slide(prs, title, points, i + 1, total_slides)

    # Add Thank You Slide
    add_thank_you(prs)

    # Save to buffer and return bytes
    buffer = io.BytesIO()
    prs.save(buffer)
    ppt_bytes = buffer.getvalue()
    buffer.close()

    return ppt_bytes