import io
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """Canvas to draw top brand bar and bottom pinned footer."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations()
            super().showPage()
        super().save()

    def draw_page_decorations(self):
        self.saveState()
        
        # 1. Top Decorative Brand Bar (Blue)
        self.setFillColor(colors.HexColor("#2563EB"))
        self.rect(0, A4[1] - 6, A4[0], 6, fill=True, stroke=False)

        # 2. Bottom Pinned Footer
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#94A3B8"))
        footer_text = "Generated By CortexAI"
        self.drawCentredString(A4[0] / 2.0, 30, footer_text)
        
        self.restoreState()


def generate_pdf(data: dict) -> bytes:
    """
    Generates a stylized PDF buffer from dictionary input.
    """
    buffer = io.BytesIO()
    
    # Document Setup with 50pt (~18mm) margins
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=50,
        rightMargin=50,
        topMargin=50,
        bottomMargin=50,
        title=data.get("title", "Document"),
        author="CortexAI",
        creator="CortexAI"
    )

    story = []
    
    # --- Color Palette ---
    PRIMARY_COLOR = colors.HexColor("#2563EB")
    HEADING_COLOR = colors.HexColor("#0F172A")
    TEXT_COLOR = colors.HexColor("#334155")
    BORDER_COLOR = colors.HexColor("#E2E8F0")

    # --- Styles ---
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=HEADING_COLOR,
        spaceAfter=6
    )

    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=TEXT_COLOR,
        spaceAfter=12
    )

    section_heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=PRIMARY_COLOR,
        spaceBefore=14,
        spaceAfter=6
    )

    bullet_style = ParagraphStyle(
        'BulletPoint',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=TEXT_COLOR,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=4
    )

    # 1. Title
    story.append(Paragraph(data.get("title", "Untitled Document"), title_style))

    # 2. Subtitle
    if data.get("subtitle"):
        story.append(Paragraph(data.get("subtitle"), subtitle_style))

    # 3. Horizontal Separator Line
    story.append(HRFlowable(
        width="100%",
        thickness=1,
        color=BORDER_COLOR,
        spaceBefore=8,
        spaceAfter=12
    ))

    # 4. Sections & Bullet Points
    sections = data.get("sections", [])
    for idx, section in enumerate(sections):
        heading = section.get("heading", f"Section {idx + 1}")
        story.append(Paragraph(heading, section_heading_style))

        for point in section.get("points", []):
            formatted_point = f"&bull;&nbsp;&nbsp;{point}"
            story.append(Paragraph(formatted_point, bullet_style))

        story.append(Spacer(1, 8))

    # Build PDF with custom canvas footer
    doc.build(story, canvasmaker=NumberedCanvas)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes