import os
import httpx
from fastapi import HTTPException, status
from pydantic import BaseModel, Field
from graph.graph import agent_app
from config.memory import add_message, get_memory
import redis.asyncio as redis
from typing import Optional

# 1. Define the incoming request schema validation payload
class AgentRequestPayload(BaseModel):
    prompt: str
    conversationId: str 
    agent: Optional[str] = "auto"
    artifacts: Optional[list] = []
    userId: Optional[str] = None

# 2. Main execution controller
async def handle_agent_request(payload: AgentRequestPayload, x_user_id: Optional[str] = None):
    # Extract structural URLs out of the service environment config
    chat_service_url = os.getenv("CHAT_SERVICE_URL", "http://127.0.0.1:8002")
    
    # B. Save to MongoDB (via Chat Microservice)
    # Step A: Save user query thread state via internal microservice call (Axios equivalent)
    async with httpx.AsyncClient(timeout=30.0) as client:
        try:
            save_payload = {
                "conversationId": payload.conversationId,
                "role": "user",
                "content": payload.prompt, 
                "images": []
            }
            # Hit the save-message route exposed by your chat microservice
            save_response = await client.post(
                f"{chat_service_url}/chat/message/save",
                json=save_payload
            )
            save_response.raise_for_status()
        except Exception as err:
            print(f"⚠️ Warning: Could not save incoming message to database: {err}")
            # We continue execution so the AI graph doesn't crash if DB sync lags

    # Step B: Prepare initial dict payload conforming to AgentState
    initial_state = {
        "prompt": payload.prompt,
        "conversationId": payload.conversationId,
        "agent": payload.agent,
        "userId": x_user_id,
        "messages": [] # LangGraph message array initialization placeholder
    }

    try:
        print(f"🚀 Initializing LangGraph run for room: {payload.conversationId}")
        
        # Step C: Invoke the compiled graph asynchronously
        result = await agent_app.ainvoke(initial_state)
        
        # Step D: Pull structural aiResponse out of the finished state dictionary
        ai_output = result.get("aiResponse", "No response generated by the workflow.")
        images = result.get("images", [])
        artifacts = result.get("artifacts", [])

        # Convert any LangChain Message objects in `images` to standard strings
        formatted_images = []
        for img in images:
            if hasattr(img, "content"):
                # If it's a LangChain message object, extract its content string
                formatted_images.append(str(img.content))
            else:
                # If it's already a string URL
                formatted_images.append(str(img))

        # clear_redis_memory()
        # A. Saving both HUman & AI response to Redis memory
        try:
            await add_message(payload.conversationId, "user", payload.prompt)
            await add_message(payload.conversationId, "assistant", ai_output)
        except Exception as err:
            print(f"⚠️ Warning: Redis save error: {err}")

        # B. Save AI response to MongoDB (via Chat Microservice)
        # STEP E: Save AI assistant response to the database
        async with httpx.AsyncClient(timeout=30.0) as client:
            if payload.conversationId and payload.conversationId.strip() != "":
                try:
                    save_ai_payload = {
                        "conversationId": payload.conversationId,
                        "role": "assistant", # Marked as assistant response
                        "content": ai_output,
                        "images": formatted_images,
                        "artifacts": artifacts
                    }
                    save_ai_res = await client.post(
                        f"{chat_service_url}/chat/message/save",
                        json=save_ai_payload
                    )
                    save_ai_res.raise_for_status()
                except Exception as err:
                    print(f"⚠️ Warning: Could not save AI message to database: {err}")
        
        return {
            "answer": ai_output,
            "images": images,
            "artifacts": artifacts
        }

    except Exception as error:
        print(f"❌ LangGraph Runtime Exception: {error}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"agent error: {str(error)}"
        )
    

async def clear_redis_memory():
    # Connect to local or configured Redis instance
    r = redis.from_url("redis://localhost:6379")
    
    # Clear only current database
    await r.flushdb()
    
    # OR clear everything across all DBs:
    # await r.flushall()
    
    print("🧹 Redis cache cleared!")