import os
import httpx
from fastapi import HTTPException, status
from pydantic import BaseModel, Field
from graph.graph import agent_app

# 1. Define the incoming request schema validation payload
class AgentRequestPayload(BaseModel):
    prompt: str
    conversationId: str 

# 2. Main execution controller
async def handle_agent_request(payload: AgentRequestPayload):
    # Extract structural URLs out of the service environment config
    chat_service_url = os.getenv("CHAT_SERVICE_URL", "http://127.0.0.1:8002")
    
    # Step A: Save user query thread state via internal microservice call (Axios equivalent)
    async with httpx.AsyncClient() as client:
        try:
            save_payload = {
                "conversationId": payload.conversationId,
                "role": "user",
                "content": payload.prompt
            }
            # Hit the save-message route exposed by your chat microservice
            save_response = await client.post(
                f"{chat_service_url}/chat/message/save",
                json=save_payload
            )
            save_response.raise_for_status()
        except Exception as err:
            print(f"⚠️ Warning: Could not save incoming message to database: {err}")
            # We continue execution so the AI graph doesn't crash if DB sync lags

    # Step B: Prepare initial dict payload conforming to AgentState
    initial_state = {
        "prompt": payload.prompt,
        "conversationId": payload.conversationId,
        "messages": [] # LangGraph message array initialization placeholder
    }

    try:
        print(f"🚀 Initializing LangGraph run for room: {payload.conversationId}")
        
        # Step C: Invoke the compiled graph asynchronously
        result = await agent_app.ainvoke(initial_state)
        
        # Step D: Pull structural aiResponse out of the finished state dictionary
        ai_output = result.get("aiResponse", "No response generated by the workflow.")
        
        return {"response": ai_output}

    except Exception as error:
        print(f"❌ LangGraph Runtime Exception: {error}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"agent error: {str(error)}"
        )